from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _

# ============================================================================
# 1. Custom User Manager
# ============================================================================
class CustomUserManager(BaseUserManager):
    """
    Custom manager to handle user creation with 'email' as the unique identifier
    instead of 'username'.
    """
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError(_('The Email field must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        # Django handles password hashing automatically via set_password
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('role', 'superadmin') # Automatically assign superadmin role
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))

        return self.create_user(email, password, **extra_fields)

# ============================================================================
# 2. User Model
# ============================================================================
class User(AbstractUser):
    """
    Custom User model where email is the unique identifier.
    """
    # Role Constants
    ROLE_CHOICES = (
        ('superadmin', 'Super Admin'),
        ('manager', 'Manager'),
        ('tech', 'Technician'),
    )

    # Remove the default username field
    username = None 
    
    # Custom fields
    name = models.CharField(max_length=255, verbose_name=_("Full Name"))
    email = models.EmailField(_('email address'), unique=True)
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='tech')
    department = models.CharField(max_length=100, default='General')
    
    # Timestamps
    updated_at = models.DateTimeField(auto_now=True)

    # Configuration for Email Authentication
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name'] # Prompt for 'name' when creating a superuser

    objects = CustomUserManager()

    def __str__(self):
        return f"{self.email} ({self.role})"

# ============================================================================
# 3. Device Model
# ============================================================================
class UserDevice(models.Model):
    """
    Model to track user devices for security and session management.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='devices')
    
    # Unique identifier for the device (generated by frontend)
    device_id = models.CharField(max_length=255) 
    
    # Device Metadata
    browser = models.CharField(max_length=100, blank=True, null=True)
    browser_version = models.CharField(max_length=50, blank=True, null=True)
    os = models.CharField(max_length=50, blank=True, null=True)
    os_version = models.CharField(max_length=50, blank=True, null=True)
    device_type = models.CharField(max_length=50, blank=True, null=True)
    
    # Last used timestamp
    date = models.DateTimeField(auto_now=True) 

    class Meta:
        # Compound Index: Ensures device_id is unique per user
        unique_together = ('user', 'device_id')
        ordering = ['-date']

    def __str__(self):
        return f"{self.user.name} - {self.device_type} ({self.browser})"