# Generated by Django 5.2.10 on 2026-01-10 11:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('filter_end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('dispatch_date', models.CharField(blank=True, default='', max_length=50)),
                ('total_work_orders', models.IntegerField(default=0)),
                ('source', models.CharField(default='external-dashboard', max_length=100)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dashboard_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_color', models.CharField(blank=True, default='', max_length=50)),
                ('priority_name', models.CharField(blank=True, default='', max_length=100)),
                ('work_order_number', models.CharField(db_index=True, max_length=100)),
                ('customer_po', models.CharField(blank=True, default='', max_length=100)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('tech_name', models.CharField(blank=True, default='', max_length=100)),
                ('technician', models.CharField(blank=True, default='', max_length=100)),
                ('promised_appointment', models.CharField(blank=True, default='', max_length=100)),
                ('created_date', models.CharField(blank=True, default='', max_length=100)),
                ('requested_date', models.CharField(blank=True, default='', max_length=100)),
                ('completed_date_str', models.CharField(blank=True, default='', max_length=100)),
                ('task', models.TextField(blank=True, default='')),
                ('task_duration', models.CharField(blank=True, default='', max_length=50)),
                ('purchase_status', models.CharField(blank=True, default='', max_length=100)),
                ('purchase_status_name', models.CharField(blank=True, default='', max_length=100)),
                ('serial', models.IntegerField(default=0)),
                ('assigned', models.BooleanField(default=False)),
                ('dispatched', models.BooleanField(default=False)),
                ('scheduled', models.BooleanField(default=False)),
                ('scheduled_date', models.CharField(blank=True, default='', max_length=100)),
                ('locates_called', models.BooleanField(default=False, help_text='Indicates if utility locates have been called in')),
                ('call_type', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('EMERGENCY', 'Emergency')], max_length=20, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('called_by', models.CharField(blank=True, default='', max_length=100)),
                ('completion_date', models.DateTimeField(blank=True, help_text='Date/Time when timer expires', null=True)),
                ('manually_tagged', models.BooleanField(default=False)),
                ('tagged_by', models.CharField(blank=True, default='', max_length=100)),
                ('tagged_at', models.DateTimeField(blank=True, null=True)),
                ('timer_started', models.BooleanField(default=False)),
                ('timer_expired', models.BooleanField(default=False)),
                ('workflow_status', models.CharField(choices=[('CALL_NEEDED', 'Call Needed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('type', models.CharField(default='STANDARD', max_length=50)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='locates.dashboarddata')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['priority_name'], name='locates_wor_priorit_9572f9_idx'), models.Index(fields=['locates_called'], name='locates_wor_locates_e5a081_idx'), models.Index(fields=['workflow_status'], name='locates_wor_workflo_e41916_idx'), models.Index(fields=['completion_date'], name='locates_wor_complet_cfa251_idx')],
            },
        ),
    ]
