# Generated by Django 5.2.10 on 2026-01-14 08:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('filter_end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('total_work_orders', models.IntegerField(default=0)),
                ('total_deleted_work_orders', models.IntegerField(default=0)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dashboard_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletedWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_color', models.CharField(default='', max_length=50)),
                ('priority_name', models.CharField(default='', max_length=100)),
                ('work_order_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('customer_po', models.CharField(default='', max_length=100)),
                ('customer_name', models.CharField(default='', max_length=200)),
                ('customer_address', models.TextField(default='')),
                ('tags', models.TextField(default='')),
                ('tech_name', models.CharField(default='', max_length=100)),
                ('created_date', models.CharField(default='', max_length=50)),
                ('requested_date', models.CharField(default='', max_length=50)),
                ('completed_date_str', models.CharField(default='', max_length=50)),
                ('task', models.TextField(default='')),
                ('serial', models.IntegerField(default=0)),
                ('scheduled_date', models.CharField(default='', max_length=50)),
                ('locates_called', models.BooleanField(default=False)),
                ('call_type', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('EMERGENCY', 'Emergency')], max_length=20, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('called_by', models.CharField(default='', max_length=100)),
                ('called_by_email', models.CharField(default='', max_length=100)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('timer_started', models.BooleanField(default=False)),
                ('timer_expired', models.BooleanField(default=False)),
                ('time_remaining', models.CharField(default='', max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_by', models.CharField(default='', max_length=100)),
                ('deleted_by_email', models.CharField(default='', max_length=100)),
                ('deleted_from', models.CharField(default='Dashboard', max_length=50)),
                ('original_work_order_id', models.IntegerField(blank=True, null=True)),
                ('is_permanently_deleted', models.BooleanField(default=False)),
                ('permanently_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('restored_by', models.CharField(default='', max_length=100)),
                ('restored_by_email', models.CharField(default='', max_length=100)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_work_orders', to='locates.dashboarddata')),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_color', models.CharField(default='', max_length=50)),
                ('priority_name', models.CharField(default='', max_length=100)),
                ('work_order_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('customer_po', models.CharField(default='', max_length=100)),
                ('customer_name', models.CharField(default='', max_length=200)),
                ('customer_address', models.TextField(default='')),
                ('tags', models.TextField(default='')),
                ('tech_name', models.CharField(default='', max_length=100)),
                ('created_date', models.CharField(default='', max_length=50)),
                ('requested_date', models.CharField(default='', max_length=50)),
                ('completed_date_str', models.CharField(default='', max_length=50)),
                ('task', models.TextField(default='')),
                ('serial', models.IntegerField(default=0)),
                ('scheduled_date', models.CharField(default='', max_length=50)),
                ('locates_called', models.BooleanField(default=False)),
                ('call_type', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('EMERGENCY', 'Emergency')], max_length=20, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('called_by', models.CharField(default='', max_length=100)),
                ('called_by_email', models.CharField(default='', max_length=100)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('timer_started', models.BooleanField(default=False)),
                ('timer_expired', models.BooleanField(default=False)),
                ('time_remaining', models.CharField(default='', max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('workflow_status', models.CharField(default='PENDING', max_length=50)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='locates.dashboarddata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
