# Generated by Django 5.2.10 on 2026-01-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('filter_end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('total_work_orders', models.IntegerField(default=0)),
                ('total_deleted_work_orders', models.IntegerField(default=0)),
                ('total_active_deleted_work_orders', models.IntegerField(default=0)),
                ('total_permanently_deleted_work_orders', models.IntegerField(default=0)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'locates_dashboarddata',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletedWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_color', models.CharField(blank=True, default='', max_length=50)),
                ('priority_name', models.CharField(blank=True, default='', max_length=50)),
                ('work_order_number', models.CharField(blank=True, default='', max_length=100)),
                ('customer_po', models.CharField(blank=True, default='', max_length=100)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=200)),
                ('tech_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_date', models.CharField(blank=True, default='', max_length=50)),
                ('requested_date', models.CharField(blank=True, default='', max_length=50)),
                ('completed_date', models.CharField(blank=True, default='', max_length=50)),
                ('task', models.TextField(blank=True, default='')),
                ('serial', models.IntegerField(default=0)),
                ('scheduled_date', models.CharField(blank=True, default='', max_length=50)),
                ('locates_called', models.BooleanField(default=False)),
                ('call_type', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('EMERGENCY', 'Emergency'), (None, 'None')], max_length=20, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('called_by', models.CharField(blank=True, default='', max_length=100)),
                ('called_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('timer_started', models.BooleanField(default=False)),
                ('timer_expired', models.BooleanField(default=False)),
                ('time_remaining', models.CharField(blank=True, default='', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.CharField(blank=True, default='', max_length=100)),
                ('deleted_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('deleted_from', models.CharField(choices=[('Dashboard', 'Dashboard'), ('AssignedDashboard', 'AssignedDashboard'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('original_work_order_id', models.IntegerField(blank=True, null=True)),
                ('is_permanently_deleted', models.BooleanField(default=False)),
                ('permanently_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('restored_by', models.CharField(blank=True, default='', max_length=100)),
                ('restored_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_work_orders', to='locates.dashboarddata')),
                ('original_dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locates.dashboarddata')),
            ],
            options={
                'db_table': 'locates_deletedworkorder',
                'indexes': [models.Index(fields=['work_order_number'], name='locates_del_work_or_76199a_idx'), models.Index(fields=['-deleted_at'], name='locates_del_deleted_cabb4b_idx'), models.Index(fields=['is_permanently_deleted'], name='locates_del_is_perm_3026c9_idx'), models.Index(fields=['restored'], name='locates_del_restore_153268_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_color', models.CharField(blank=True, default='', max_length=50)),
                ('priority_name', models.CharField(blank=True, default='', max_length=50)),
                ('work_order_number', models.CharField(blank=True, default='', max_length=100)),
                ('customer_po', models.CharField(blank=True, default='', max_length=100)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=200)),
                ('tech_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_date', models.CharField(blank=True, default='', max_length=50)),
                ('requested_date', models.CharField(blank=True, default='', max_length=50)),
                ('completed_date', models.CharField(blank=True, default='', max_length=50)),
                ('task', models.TextField(blank=True, default='')),
                ('serial', models.IntegerField(default=0)),
                ('scheduled_date', models.CharField(blank=True, default='', max_length=50)),
                ('locates_called', models.BooleanField(default=False)),
                ('call_type', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('EMERGENCY', 'Emergency'), (None, 'None')], max_length=20, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('called_by', models.CharField(blank=True, default='', max_length=100)),
                ('called_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('timer_started', models.BooleanField(default=False)),
                ('timer_expired', models.BooleanField(default=False)),
                ('time_remaining', models.CharField(blank=True, default='', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='locates.dashboarddata')),
            ],
            options={
                'db_table': 'locates_workorder',
                'indexes': [models.Index(fields=['work_order_number'], name='locates_wor_work_or_b3df7f_idx')],
            },
        ),
    ]
