# Generated by Django 5.2.10 on 2026-01-12 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='workorder',
            name='locates_wor_priorit_9572f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='workorder',
            name='locates_wor_locates_e5a081_idx',
        ),
        migrations.RemoveIndex(
            model_name='workorder',
            name='locates_wor_workflo_e41916_idx',
        ),
        migrations.RemoveIndex(
            model_name='workorder',
            name='locates_wor_complet_cfa251_idx',
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='dashboard_metadata',
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='dispatch_date',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='technician',
        ),
        migrations.AddField(
            model_name='workorder',
            name='called_by_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='tagged_by_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='time_remaining',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='call_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workOrders', to='locates.dashboarddata'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='locates_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='task_duration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='type',
            field=models.CharField(choices=[('STANDARD', 'STANDARD'), ('EMERGENCY', 'EMERGENCY'), ('EXCAVATOR', 'EXCAVATOR')], default='STANDARD', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_order_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workflow_status',
            field=models.CharField(choices=[('CALL_NEEDED', 'CALL_NEEDED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETE', 'COMPLETE'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=20),
        ),
    ]
