# Generated by Django 5.2.10 on 2026-01-14 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='source',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='dispatched',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='manually_tagged',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='promised_appointment',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='purchase_status',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='purchase_status_name',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='scheduled',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='tagged_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='tagged_by',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='tagged_by_email',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='task_duration',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='type',
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='dashboard_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='total_active_deleted_work_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='total_deleted_work_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='total_permanently_deleted_work_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='filter_end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='filter_start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='scraped_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='call_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='locates.dashboarddata'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='priority_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_order_number',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workflow_status',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.CreateModel(
            name='DeletedWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_color', models.CharField(blank=True, default='', max_length=50)),
                ('priority_name', models.CharField(blank=True, default='', max_length=50)),
                ('work_order_number', models.CharField(db_index=True, default='', max_length=100)),
                ('customer_po', models.CharField(blank=True, default='', max_length=100)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('tags', models.TextField(blank=True, default='')),
                ('tech_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_date', models.CharField(blank=True, default='', max_length=100)),
                ('requested_date', models.CharField(blank=True, default='', max_length=100)),
                ('completed_date_str', models.CharField(blank=True, default='', max_length=100)),
                ('task', models.TextField(blank=True, default='')),
                ('serial', models.IntegerField(default=0)),
                ('scheduled_date', models.CharField(blank=True, default='', max_length=100)),
                ('locates_called', models.BooleanField(default=False)),
                ('call_type', models.CharField(blank=True, max_length=20, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('called_by', models.CharField(blank=True, default='', max_length=100)),
                ('called_by_email', models.CharField(blank=True, default='', max_length=100)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('timer_started', models.BooleanField(default=False)),
                ('timer_expired', models.BooleanField(default=False)),
                ('time_remaining', models.CharField(blank=True, default='', max_length=100)),
                ('workflow_status', models.CharField(default='UNKNOWN', max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('deleted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('deleted_by', models.CharField(default='', max_length=100)),
                ('deleted_by_email', models.CharField(default='', max_length=100)),
                ('deleted_from', models.CharField(default='Unknown', max_length=50)),
                ('original_work_order_id', models.IntegerField(blank=True, null=True)),
                ('is_permanently_deleted', models.BooleanField(db_index=True, default=False)),
                ('permanently_deleted_at', models.DateTimeField(default=None, null=True)),
                ('restored', models.BooleanField(db_index=True, default=False)),
                ('restored_at', models.DateTimeField(default=None, null=True)),
                ('restored_by', models.CharField(default='', max_length=100)),
                ('restored_by_email', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_work_orders', to='locates.dashboarddata')),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
