# Generated by Django 5.2.10 on 2026-01-19 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0002_workordertoday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('priority_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tech_name', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_date', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.CharField(blank=True, max_length=50, null=True)),
                ('call_type', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('EMERGENCY', 'Emergency'), (None, 'None')], max_length=20, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('called_by', models.CharField(blank=True, max_length=100, null=True)),
                ('called_by_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('locates_called', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_remaining', models.CharField(blank=True, max_length=50, null=True)),
                ('timer_started', models.BooleanField(default=False)),
                ('timer_expired', models.BooleanField(default=False)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted_by_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Locate',
                'verbose_name_plural': 'Locates',
                'db_table': 'locates_dashboard',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='deletedworkorder',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='deletedworkorder',
            name='original_dashboard',
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
        migrations.DeleteModel(
            name='DashboardData',
        ),
        migrations.DeleteModel(
            name='DeletedWorkOrder',
        ),
    ]
