# Generated by Django 5.2.10 on 2026-01-14 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0002_alter_workorder_options_remove_dashboarddata_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboarddata',
            name='total_active_deleted_work_orders',
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='total_permanently_deleted_work_orders',
        ),
        migrations.RemoveField(
            model_name='deletedworkorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deletedworkorder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='deletedworkorder',
            name='workflow_status',
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='filter_end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='filter_start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='call_type',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('EMERGENCY', 'Emergency')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='called_by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='called_by_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='completed_date_str',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='created_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='customer_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='customer_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='customer_po',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='deleted_from',
            field=models.CharField(default='Dashboard', max_length=50),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='is_permanently_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='permanently_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='priority_color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='priority_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='requested_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='restored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='scheduled_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='task',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='tech_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='time_remaining',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deletedworkorder',
            name='work_order_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='call_type',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('EMERGENCY', 'Emergency')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='called_by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='called_by_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='completed_date_str',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='customer_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='customer_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='customer_po',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='priority_color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='priority_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='requested_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='scheduled_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='task',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tech_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='time_remaining',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_order_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workflow_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
