# Generated by Django 5.2.10 on 2026-01-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0003_remove_dashboarddata_total_active_deleted_work_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedworkorder',
            name='work_order_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_order_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
